# Generated by Django 4.1.3 on 2022-11-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=155)),
                ('title', models.CharField(max_length=155)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('content', models.CharField(max_length=155)),
                ('approved', models.BooleanField()),
            ],
        ),
    ]
