# Generated by Django 4.1.3 on 2022-11-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacemonkeyapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=155),
        ),
    ]
